title: Buffy The Fluff
email: kris@krisgfx.com
description: kitty website
destination: docs
baseurl: "/buffy_fluff"
url: ""
twitter_username: 
github_username: krisgfx

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal